#!/usr/bin/env python3
"""
Simple tool to parse Verilog files and display the AST.

Usage:
    python3 parse_verilog.py examples/counter.v
    python3 parse_verilog.py examples/simple_alu.v --verbose
    python3 parse_verilog.py examples/counter.v -o counter.ast
"""

import sys
import os
import json
from pathlib import Path
from pprint import pformat

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from fpga_synth.hdl_parser.parser import parse_verilog
from fpga_synth.hdl_parser.ast_nodes import *


def print_ast_summary(ast, filename, verbose=False):
    """Parse and print a summary of the AST."""

    print(f"\n{'='*60}")
    print(f"Parsing: {filename}")
    print(f"{'='*60}\n")

    for module in ast.modules:
        print(f"Module: {module.name}")
        print(f"  Location: Line {module.line}, Col {module.col}")

        # Parameters
        if module.params:
            print(f"\n  Parameters ({len(module.params)}):")
            for param in module.params:
                print(f"    - {param.name} = {param.value}")

        # Ports
        if module.ports:
            print(f"\n  Ports ({len(module.ports)}):")
            for port in module.ports:
                width_str = ""
                if port.range:
                    width_str = f"[{port.range.msb}:{port.range.lsb}] "
                net_str = f" {port.net_type}" if port.net_type != "wire" else ""
                print(f"    - {port.direction:6} {width_str}{port.name}{net_str}")

        # Body items
        print(f"\n  Body Items ({len(module.body)}):")

        wire_decls = [item for item in module.body if isinstance(item, NetDecl)]
        if wire_decls:
            print(f"    Wire/Reg Declarations: {len(wire_decls)}")
            if verbose:
                for decl in wire_decls:
                    width_str = f"[{decl.range.msb}:{decl.range.lsb}] " if decl.range else ""
                    print(f"      - {decl.net_type} {width_str}{decl.name}")

        assigns = [item for item in module.body if isinstance(item, ContinuousAssign)]
        if assigns:
            print(f"    Continuous Assigns: {len(assigns)}")
            if verbose:
                for i, assign in enumerate(assigns, 1):
                    print(f"      {i}. assign ... (Line {assign.line})")

        always_blocks = [item for item in module.body if isinstance(item, AlwaysBlock)]
        if always_blocks:
            print(f"    Always Blocks: {len(always_blocks)}")
            for i, block in enumerate(always_blocks, 1):
                if block.is_star:
                    sens = "@(*)"
                else:
                    sens_list = []
                    for s in block.sensitivity:
                        edge = f"{s.edge} " if s.edge else ""
                        sens_list.append(f"{edge}{s.signal}")
                    sens = f"@({', '.join(sens_list)})"
                print(f"      {i}. always {sens} (Line {block.line})")
                print(f"         Statements: {len(block.body)}")

        instances = [item for item in module.body if isinstance(item, ModuleInstance)]
        if instances:
            print(f"    Module Instances: {len(instances)}")
            if verbose:
                for inst in instances:
                    print(f"      - {inst.module_name} {inst.instance_name}")

        if verbose:
            print(f"\n  Raw AST:")
            print(f"    {module}")

    print(f"\n{'='*60}")
    print("✓ Parsing successful!")
    print(f"{'='*60}\n")


def write_ast_file(ast, output_path):
    """Write AST to a file in a readable format."""
    with open(output_path, 'w') as f:
        f.write("# Abstract Syntax Tree\n")
        f.write("# Generated by fpga_synth parser\n\n")
        f.write(pformat(ast, width=100, indent=2))
    print(f"\n✓ AST written to: {output_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 parse_verilog.py <verilog_file> [options]")
        print("\nOptions:")
        print("  --verbose, -v     Show detailed AST information")
        print("  --output, -o      Output AST to file (default: <input>.ast)")
        print("\nExamples:")
        print("  python3 parse_verilog.py examples/counter.v")
        print("  python3 parse_verilog.py examples/simple_alu.v --verbose")
        print("  python3 parse_verilog.py examples/counter.v -o counter.ast")
        sys.exit(1)

    verilog_file = Path(sys.argv[1])
    verbose = "--verbose" in sys.argv or "-v" in sys.argv

    # Check for output file option
    output_file = None
    if "--output" in sys.argv or "-o" in sys.argv:
        try:
            idx = sys.argv.index("--output") if "--output" in sys.argv else sys.argv.index("-o")
            if idx + 1 < len(sys.argv):
                output_file = Path(sys.argv[idx + 1])
            else:
                output_file = verilog_file.with_suffix('.ast')
        except (ValueError, IndexError):
            output_file = verilog_file.with_suffix('.ast')
    else:
        # Default: always write .ast file
        output_file = verilog_file.with_suffix('.ast')

    if not verilog_file.exists():
        print(f"Error: File not found: {verilog_file}")
        sys.exit(1)

    try:
        # Read and parse the file
        source_code = verilog_file.read_text()
        ast = parse_verilog(source_code, str(verilog_file))

        # Print summary
        print_ast_summary(ast, verilog_file.name, verbose)

        # Write AST to file
        write_ast_file(ast, output_file)

    except Exception as e:
        print(f"\n❌ Error parsing {verilog_file}:")
        print(f"   {e}\n")
        if verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
